/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import static demo.BubbleChartDemo1.createDataset;
import javax.swing.JFrame;  
import javax.swing.SwingUtilities;  
import javax.swing.WindowConstants;
  

  
import org.jfree.chart.ChartFactory;  
import org.jfree.chart.ChartPanel;  
import org.jfree.chart.JFreeChart;  
import org.jfree.data.category.DefaultCategoryDataset;  
/**
 *
 * @author ghias
 */
public class JChartLine extends JFrame {

    /**
     * Creates new form JChartLine
     */
    public JChartLine(String title) {
        super(title);  
    // Create dataset  
    DefaultCategoryDataset dataset = createDataset();  
    // Create chart  
    JFreeChart chart = ChartFactory.createLineChart(  
        "Site Traffic", // Chart title  
        "Date", // X-Axis Label  
        "Number of Visitor", // Y-Axis Label  
        dataset  
        );  
  
    ChartPanel panel = new ChartPanel(chart);  
    setContentPane(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private DefaultCategoryDataset createDataset() {  
  
    String series1 = "Visitor";  
    String series2 = "Unique Visitor";  
  
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
  
    dataset.addValue(200, series1, "2016-12-19");  
    dataset.addValue(150, series1, "2016-12-20");  
    dataset.addValue(100, series1, "2016-12-21");  
    dataset.addValue(210, series1, "2016-12-22");  
    dataset.addValue(240, series1, "2016-12-23");  
    dataset.addValue(195, series1, "2016-12-24");  
    dataset.addValue(245, series1, "2016-12-25");  
  
    dataset.addValue(150, series2, "2016-12-19");  
    dataset.addValue(130, series2, "2016-12-20");  
    dataset.addValue(95, series2, "2016-12-21");  
    dataset.addValue(195, series2, "2016-12-22");  
    dataset.addValue(200, series2, "2016-12-23");  
    dataset.addValue(180, series2, "2016-12-24");  
    dataset.addValue(230, series2, "2016-12-25");  
  
    return dataset;  
  }  
  
  public static void main(String[] args) {  
    SwingUtilities.invokeLater(() -> {  
      JChartLine example = new JChartLine("Line Chart Example");  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
    });  
  }  
}
